### ISSUE TITLE
The difference between 'mTREx' and 'mTRExf'?

### ISSUE THREAD

**Issue by mjeensung** [jzbjyb/X-FACTR#6]
Hello

I was wondering what the difference between 'mTREx' and 'mTRExf' is.
I read the paper but couldn't find out the difference and which data you used.

**Comment by jzbjyb** [comment]
Hi @mjeensung, thanks for your question!
`mTRExf` is the dataset we used in our paper where we sample facts with probability proportional to their frequency (as mentioned in section 3.2), while facts in `mTREx` are sampled uniformly.

**Comment by mjeensung** [comment]
Thank you for your quick reply, @jzbjyb!
